config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :bikes, only: [:index, :show] do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :bookings, only: [:create]
  end
  get 'mybookings', to: 'bookings#mybookings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :favorites
  has_many :bookings
  validates :description, :price, :name, :photo, presence: true
  # validates :price, numericality: true
  # validates :price, numericality: { only_integer: true }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :booking_start, :booking_end, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/reservations.rb
class Reservations < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  validates :note, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bikes
  has_many :favorites
  # to access bikes
  has_many :bikes, through: :favorites
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if params[:query].present?
      @bikes = Bike.near(params[:query], 50)
    else
      @bikes = Bike.near('Aubagne', 50)
    end
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url('picto.png')
      }
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
    @booking.user = current_user
    if @booking.save
      redirect_to mybookings_path
    else
      render "bikes/show"
    end
  end

  def mybookings
    @bookings = current_user.bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_start, :booking_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h2><%= bike.name %></h2>
<%= image_tag(bike.photo, size: "150x150") %>
<h5> <%= bike.price%> €</h5>

app/views/bikes/index.html.erb
<%= render 'shared/search' %>
<div class="content">
  <div class="cards">
    <% @bikes.each do |bike| %>
      <div class="cardbike">
        <div class="card-trip">
          <%= image_tag bike.photo %>
        </div>
        <div class="card-trip-infos">
          <i class="far fa-heart" id="icone-add-like"></i>
          <div class= "adding padding">
          <h3> <%= bike.name %> </h3>
          <p> <%= bike.description %> </p>
          </div>
          <div class="star">
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
            </div>
          <p class="card-trip-pricing"> <%= bike.price %> €</p>
          <!-- <a class="btn btn-ghost" href="#">Découvrir</a> -->
          <%= link_to "découvrir", bike, class: "btn btn-ghost" %>
     </div>
      </div>
    <% end %>
  </div>
  <div id="map"
       style="width: 40%; height: 100vh;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>
 <!-- <i class="fas fa-heart"></i>-->

app/views/bikes/show.html.erb
<div id="description-show">
<h3> <%= @bike.name %> </h3>
<p> <%= @bike.description %> </p>
</div>
<div class="star">
  <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
</div>
<i class="far fa-heart" id="icone-add-like-show"></i>
<div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url @bike.photo %>);">
</div>
<div class="global">
    <div class="gauche">
       <p class="description-longue">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercice ullamco laboris nisi ut aliquip ex ea commodo conséquat. Duis aute irure dolor in reprehenderit in voluptateit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sauf sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <div class="droite">
      <%= simple_form_for [ @bike, @booking ]  do |f| %>
      <%= f.input :booking_start %>
      <%= f.input :booking_end %>
      <%= f.submit "book the bike", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/mybookings.html.erb
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="style.css">
  <link rel=“stylesheet” href=“https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css” integrity=“sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u” crossorigin=“anonymous”>
</head>

<body>
  <%= render 'shared/search' %>
  <h3>Mes vélos:</h3>
 <!--  <br>
  <a class="btn btn-page4" href="#">Précédents</a>
  <a class="btn btn-page4" href="#">A venir</a>
  <a class="btn btn-page4" href="#">Mes envies</a>
  <br>
  <br> -->
<nav>
  <% @bookings.each do |booking|  %>
    <div class="card-trip-order">
          <%= image_tag booking.bike.photo %>
          <div class="card-trip-order-infos">
            <div>
              <h2><%= booking.bike.name %></h2>
              <p><%= booking.bike.description %></p>
              <p> Du <%= booking.booking_start.day %> / <%= booking.booking_start.month %> / <%= booking.booking_start.year %>
              au <%= booking.booking_end.day %> / <%= booking.booking_end.month %> / <%= booking.booking_end.year %> </p>
            </div>
            <br>
            <!-- <a class="btn btn-validate" href="#">Envoyer</a> -->
          </div>
          <%= render 'shared/ratingstars' %>
        </div>
  <% end %>
</nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bretzel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url('background-home.jpg') %>);">
  <div class="container">
    <h1>Louez votre vélo sur Bretzel!</h1>
    <%= render 'shared/search' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to bikes_path, class: "navbar-brand" do %>
      <%= image_tag("logo-blanc.png", class: "img-responsive", id: "navbar-logo") %>
      <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <% if user_signed_in? %>
        <ul class="navbar-nav hote">
          <li>
            <%= link_to "Mes réservations", mybookings_path, class: "nav-link" %>
          </li>
         </ul>
        <li class="nav-item">
          <%= link_to "", destroy_user_session_path, :method => :delete, class: "fas fa-user-circle profil-color-on" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "", new_user_session_path, class: "far fa-user-circle profil-color-off" %>
        </li>
      <% end %>
  </div>
</div>

app/views/shared/_ratingstars.html.erb
<div class="rate">
    <input type="radio" id="star5" name="rate" value="5" />
    <label for="star5" title="text">5 stars</label>
    <input type="radio" id="star4" name="rate" value="4" />
    <label for="star4" title="text">4 stars</label>
    <input type="radio" id="star3" name="rate" value="3" />
    <label for="star3" title="text">3 stars</label>
    <input type="radio" id="star2" name="rate" value="2" />
    <label for="star2" title="text">2 stars</label>
    <input type="radio" id="star1" name="rate" value="1" />
    <label for="star1" title="text">1 star</label>
</div>

app/views/shared/_search.html.erb
<%= form_tag bikes_path, method: :get, class: "search-geo-controls input-group rounded search_style" do %>
  <div><%= text_field_tag :query,
                          params[:query],
                          class: "form-control rounded size-text",
                          placeholder: "Choisissez votre ville pour louer votre vélo"
  %></div>
  <%= button_tag(type: 'submit', class:'btn btn-info') do %>
    <i class="fas fa-search"></i>
  <% end %>
<!--  <button id="locate-me" class="btn btn-info ml-3" style="width: 200px;">Me géolocaliser</button>-->
<% end %>